version: '3'

services:
  issl-growi:
    container_name: issl-growi
    build:
      context: ./growi
      dockerfile: Dockerfile
    image: issl-growi-img
    ports:
      - 127.0.0.1:3000:3000    # localhost only by default
    links:
      - issl-mongo:issl-mongo
      - issl-elasticsearch:issl-elasticsearch
    environment:
      - MONGO_URI=mongodb://issl-mongo:27017/growi
      - ELASTICSEARCH_URI=http://issl-elasticsearch:9200/growi
      - PASSWORD_SEED=password
      - FILE_UPLOAD=local
      - MATHJAX=1
      - HACKMD_URI=http://127.0.0.1:3100
      - HACKMD_URI_FOR_SERVER=http://127.0.0.1:3100
    entrypoint: "dockerize
                  -wait tcp://issl-mongo:27017
                  -wait tcp://issl-elasticsearch:9200
                  -timeout 60s
                  /docker-entrypoint.sh"
    command: ["yarn migrate && node -r dotenv-flow/config --expose_gc dist/server/app.js"]
    depends_on:
      - issl-mongo
      - issl-elasticsearch
    restart: unless-stopped
    volumes:
      - data-growi:/data

  issl-mongo:
    container_name: issl-mongo
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - data-mongo-config:/data/configdb
      - data-mongo:/data/db

  issl-elasticsearch:
    container_name: issl-elasticsearch
    build:
      context: .
      dockerfile: ./elasticsearch/Dockerfile
    image: issl-elasticsearch-img
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data-elasticsearch:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  issl-hackmd:
    container_name: issl-hackmd
    build:
      context: .
      dockerfile: ./hackmd/Dockerfile
    image: issl-hackmd-img
    environment:
      - GROWI_URI=http://issl-growi:3000
      - CMD_DB_URL=mysql://hackmd:hackmdpass@issl-mariadb:3306/hackmd
      - CMD_CSP_ENABLE=false
    ports:
      - 127.0.0.1:3100:3000   # localhost only by default
    depends_on:
      - issl-mariadb
      - issl-growi
    restart: unless-stopped

  issl-mariadb:
    container_name: issl-mariadb
    image: mariadb:10.3
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_USER=hackmd
      - MYSQL_PASSWORD=hackmdpass
      - MYSQL_DATABASE=hackmd
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    restart: unless-stopped
    volumes:
      - data-mariadb:/var/lib/mysql

volumes:
  data-growi:
  data-mongo:
  data-mongo-config:
  data-elasticsearch:
  data-mariadb:

